# Generated by Django 2.0.1 on 2018-01-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserEmail', models.EmailField(max_length=254, unique=True)),
                ('UserPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('PhoneNum', models.CharField(max_length=30)),
                ('UserEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetWorkManage.User')),
            ],
        ),
    ]

#
# BEGIN;
# --
# -- Create model User
# --
# CREATE TABLE "NetWorkManage_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "UserEmail" varchar(254) NOT NULL UNIQUE, "UserPassword" varchar(30) NOT NULL);
# --
# -- Create model UserInfo
# --
# CREATE TABLE "NetWorkManage_userinfo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "info" text NOT NULL, "PhoneNum" varchar(30) NOT NULL, "UserEmail_id" integer NOT NULL REFERENCES "NetWorkManage_user" ("id") DEFERRABLE INITIALLY DEFERRED)
# ;
# CREATE INDEX "NetWorkManage_userinfo_UserEmail_id_79f7bd68" ON "NetWorkManage_userinfo" ("UserEmail_id");
# COMMIT;
