# Generated by Django 2.0.1 on 2018-01-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetWorkManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserEmail',
            new_name='User',
        ),
    ]
